platform: maixcam2

debug_console_enabled: false
display_enabled: true

cameras:
  - camera_id: "main"
    source: null
    width: 640
    height: 640
    camera_stream_queue_size: 3

uart_defaults:
  port: "/dev/ttyS4"
  baudrate: 115200

ai:
  models:
    - nick_name: "yolo11n"
      model: "/root/models/steelball_640.mud"
      model_type: "auto"
    - nick_name: "plate_seg"
      model: "/root/models/steelsheet_640.mud"
      model_type: "auto"
  active: "yolo11n"
  #active: "plate_seg"  # switch to seg model for steel plate detection
